name: lanwash
description: LanWash — приложение для записи на автомойку
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.20.2
  http: ^1.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.6
  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.1.0
  file_saver: ^0.3.1
  file_picker: ^8.0.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  get_it: ^8.0.0
  firebase_app_check: ^0.4.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/icon3.png"

  ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
