#!/usr/bin/env python3
"""Locust load testing scenarios for LanWash API."""

import json
import random
from datetime import datetime, timedelta

from locust import HttpUser, between, task

# Test credentials generated by seed.py
TEST_PASSWORD = "testpass123"


class AnonymousUser(HttpUser):
    """Unauthenticated user — only public endpoints."""

    weight = 1
    wait_time = between(1, 5)

    @task(3)
    def health_check(self):
        self.client.get("/health")

    @task(1)
    def login_attempt(self):
        self.client.post(
            "/api/auth/login",
            json={
                "username": "nonexistent_user",
                "password": "wrongpass",
            },
        )


class ClientUser(HttpUser):
    """Authenticated client creating and managing appointments."""

    weight = 5
    wait_time = between(2, 8)

    def on_start(self):
        self.client_id = random.randint(1, 50)
        self.username = f"test_client_{self.client_id}"
        self.token = None
        self.login()

    def login(self):
        resp = self.client.post(
            "/api/auth/login",
            json={
                "username": self.username,
                "password": TEST_PASSWORD,
            },
        )
        if resp.status_code == 200:
            self.token = resp.json()["access_token"]
        else:
            print(f"Client login failed: {resp.status_code} {resp.text}")

    @task(5)
    def list_appointments(self):
        self.client.get("/api/appointments/", headers=self._auth())

    @task(3)
    def create_appointment(self):
        now = datetime.now()
        dt = now + timedelta(days=random.randint(1, 7), hours=random.randint(8, 20))
        dt = dt.replace(minute=(dt.minute // 30) * 30, second=0, microsecond=0)

        wash_types = ["w1", "w2", "w3", "w4"]
        extras_pool = ["s4", "s6", "s7", "s12", "s13", "s17"]
        extras = random.sample(extras_pool, k=random.randint(0, 3))

        import uuid as _uuid

        payload = {
            "id": str(_uuid.uuid4()),
            "clientName": f"Client {self.client_id}",
            "carModel": "Toyota Camry",
            "carNumber": "А123БВ777",
            "dateTime": dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "washTypeId": random.choice(wash_types),
            "additionalServices": json.dumps(extras),
            "ownerUsername": self.username,
            "notes": "",
        }
        resp = self.client.post(
            "/api/appointments/", json=payload, headers=self._auth()
        )
        if resp.status_code == 200:
            self.created_appointment_id = resp.json().get("id")

    @task(2)
    def get_services(self):
        self.client.get("/api/services/", headers=self._auth())

    @task(1)
    def get_promos(self):
        self.client.get("/api/services/promos", headers=self._auth())

    def _auth(self):
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}


class WasherUser(HttpUser):
    """Authenticated washer viewing shifts and updating appointments."""

    weight = 2
    wait_time = between(3, 10)

    def on_start(self):
        self.washer_id = random.randint(1, 10)
        self.username = f"test_washer_{self.washer_id}"
        self.token = None
        self.login()

    def login(self):
        resp = self.client.post(
            "/api/auth/login",
            json={
                "username": self.username,
                "password": TEST_PASSWORD,
            },
        )
        if resp.status_code == 200:
            self.token = resp.json()["access_token"]
        else:
            print(f"Washer login failed: {resp.status_code} {resp.text}")

    @task(5)
    def list_shifts(self):
        from datetime import datetime, timedelta

        today = datetime.now()
        start = today.strftime("%Y-%m-%d")
        end = (today + timedelta(days=7)).strftime("%Y-%m-%d")
        self.client.get(
            f"/api/shifts/?start_date={start}&end_date={end}", headers=self._auth()
        )

    @task(4)
    def list_appointments(self):
        self.client.get("/api/appointments/", headers=self._auth())

    @task(2)
    def get_consumables(self):
        self.client.get("/api/consumables/", headers=self._auth())

    def _auth(self):
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}


class AdminUser(HttpUser):
    """Authenticated admin viewing reports and stats."""

    weight = 1
    wait_time = between(5, 15)

    def on_start(self):
        self.admin_id = random.randint(1, 2)
        self.username = f"test_admin_{self.admin_id}"
        self.token = None
        self.login()

    def login(self):
        resp = self.client.post(
            "/api/auth/login",
            json={
                "username": self.username,
                "password": TEST_PASSWORD,
            },
        )
        if resp.status_code == 200:
            self.token = resp.json()["access_token"]
        else:
            print(f"Admin login failed: {resp.status_code} {resp.text}")

    @task(5)
    def get_admin_stats(self):
        self.client.get("/api/auth/stats/admin", headers=self._auth())

    @task(4)
    def list_all_appointments(self):
        self.client.get("/api/appointments/", headers=self._auth())

    @task(2)
    def get_consumables(self):
        self.client.get("/api/consumables/", headers=self._auth())

    @task(1)
    def get_reviews(self):
        self.client.get("/api/reviews/", headers=self._auth())

    @task(1)
    def delete_notification(self):
        self.client.delete(
            f"/api/notifications/{random.randint(1, 100)}", headers=self._auth()
        )

    def _auth(self):
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}
