#!/usr/bin/env python3
"""
Скрипт для безопасного импорта Firebase Service Account JSON в backend/.env
НИКОГДА не коммитьте JSON-файл ключей в репозиторий!

Использование:
    python backend/scripts/setup_firebase_env.py path/to/serviceAccountKey.json
"""

import json
import os
import sys
from pathlib import Path


def load_env(path: Path) -> dict:
    """Читает .env файл и возвращает словарь ключ=значение."""
    env = {}
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, value = line.split("=", 1)
                    env[key.strip()] = value.strip()
    return env


def save_env(path: Path, env: dict):
    """Сохраняет словарь в .env файл, сохраняя существующие комментарии и порядок."""
    lines = []
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            lines = f.readlines()

    # Обновляем существующие ключи
    updated_keys = set()
    new_lines = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            new_lines.append(line)
            continue
        if "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in env:
                new_lines.append(f"{key}={env[key]}\n")
                updated_keys.add(key)
            else:
                new_lines.append(line)

    # Добавляем новые ключи в конец
    new_keys = [k for k in env if k not in updated_keys]
    if new_keys:
        new_lines.append("\n# Firebase Admin SDK (auto-generated by setup_firebase_env.py)\n")
        for key in new_keys:
            new_lines.append(f"{key}={env[key]}\n")

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python setup_firebase_env.py <path/to/serviceAccountKey.json>")
        sys.exit(1)

    json_path = Path(sys.argv[1]).resolve()
    if not json_path.exists():
        print(f"Error: File not found: {json_path}")
        sys.exit(1)

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Проверяем обязательные поля
    required = ["project_id", "private_key_id", "private_key", "client_email", "client_id"]
    missing = [k for k in required if k not in data]
    if missing:
        print(f"Error: Missing fields in JSON: {missing}")
        sys.exit(1)

    # Путь к .env
    script_dir = Path(__file__).parent.resolve()
    env_path = script_dir.parent / ".env"

    env = load_env(env_path)

    # Обновляем/добавляем Firebase-переменные
    env["FIREBASE_PROJECT_ID"] = data["project_id"]
    env["FIREBASE_PRIVATE_KEY_ID"] = data["private_key_id"]
    # Сохраняем private_key в одну строку с \n для .env
    private_key = data["private_key"].replace("\n", r"\n")
    env["FIREBASE_PRIVATE_KEY"] = f'"{private_key}"'
    env["FIREBASE_CLIENT_EMAIL"] = data["client_email"]
    env["FIREBASE_CLIENT_ID"] = data["client_id"]
    env["FIREBASE_AUTH_URI"] = data.get("auth_uri", "https://accounts.google.com/o/oauth2/auth")
    env["FIREBASE_TOKEN_URI"] = data.get("token_uri", "https://oauth2.googleapis.com/token")
    env["FIREBASE_AUTH_PROVIDER_X509_CERT_URL"] = data.get(
        "auth_provider_x509_cert_url", "https://www.googleapis.com/oauth2/v1/certs"
    )
    env["FIREBASE_CLIENT_X509_CERT_URL"] = data.get("client_x509_cert_url", "")

    save_env(env_path, env)

    print(f"✅ Firebase credentials saved to {env_path}")
    print(f"   Project: {data['project_id']}")
    print(f"   Client:  {data['client_email']}")
    print()
    print("⚠️  ВАЖНО:")
    print("   1. Удалите JSON-файл после импорта или храните его ВНЕ репозитория.")
    print("   2. Убедитесь, что backend/.env указан в .gitignore.")
    print("   3. Не коммитьте .env файл!")


if __name__ == "__main__":
    main()
