// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBZiaXROmyA3ag0qkU0vCUpA8Oec_x9wM',
    appId: '1:990535392995:web:2f16e32f1f07e246242fd6',
    messagingSenderId: '990535392995',
    projectId: 'lanwash',
    authDomain: 'lanwash.firebaseapp.com',
    storageBucket: 'lanwash.firebasestorage.app',
    measurementId: 'G-WSK83JKZFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKTIyOoWPzP_1uTHcCTBFN9zsvoa8EBWU',
    appId: '1:990535392995:android:a5cce74f614cb2a3242fd6',
    messagingSenderId: '990535392995',
    projectId: 'lanwash',
    storageBucket: 'lanwash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVSou7ac6Fn4q-J7djvjQnWn1ima-QWqw',
    appId: '1:990535392995:ios:bb26dc6a918210f9242fd6',
    messagingSenderId: '990535392995',
    projectId: 'lanwash',
    storageBucket: 'lanwash.firebasestorage.app',
    iosBundleId: 'com.example.lanwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVSou7ac6Fn4q-J7djvjQnWn1ima-QWqw',
    appId: '1:990535392995:ios:bb26dc6a918210f9242fd6',
    messagingSenderId: '990535392995',
    projectId: 'lanwash',
    storageBucket: 'lanwash.firebasestorage.app',
    iosBundleId: 'com.example.lanwash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBZiaXROmyA3ag0qkU0vCUpA8Oec_x9wM',
    appId: '1:990535392995:web:7ce20fa7c04a7c5c242fd6',
    messagingSenderId: '990535392995',
    projectId: 'lanwash',
    authDomain: 'lanwash.firebaseapp.com',
    storageBucket: 'lanwash.firebasestorage.app',
    measurementId: 'G-EQK5WHB0BJ',
  );
}
