"""add_perf_indexes

Revision ID: 13bd1430d8f6
Revises: b51a9e3b42c5
Create Date: 2026-06-15 10:59:21.102669

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13bd1430d8f6"
down_revision: Union[str, Sequence[str], None] = "b51a9e3b42c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure the refill log table exists for fresh databases before adding
    # performance indexes. Production databases created via create_all already
    # have it, so use IF NOT EXISTS to stay idempotent.
    op.create_table(
        "consumable_refill_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("consumableId", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("oldStock", sa.Float(), nullable=False),
        sa.Column("newStock", sa.Float(), nullable=False),
        sa.Column("refilledBy", sa.String(), nullable=False, server_default=""),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumableId"],
            ["consumables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )

    op.create_index(
        "ix_appointments_assigned_washer",
        "appointments",
        ["assignedWasher"],
        unique=False,
    )
    op.create_index(
        "ix_appointments_hidden_admin",
        "appointments",
        ["isHiddenFromAdmin"],
        unique=False,
    )
    op.create_index(
        "ix_refill_log_consumable",
        "consumable_refill_log",
        ["consumableId"],
        unique=False,
    )
    op.create_index(
        "ix_refill_log_timestamp", "consumable_refill_log", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_usage_log_timestamp", "consumable_usage_log", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_notification_queue_sent", "notification_queue", ["sentAt"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_queue_sent", table_name="notification_queue")
    op.drop_index("ix_usage_log_timestamp", table_name="consumable_usage_log")
    op.drop_index("ix_refill_log_timestamp", table_name="consumable_refill_log")
    op.drop_index("ix_refill_log_consumable", table_name="consumable_refill_log")
    op.drop_index("ix_appointments_hidden_admin", table_name="appointments")
    op.drop_index("ix_appointments_assigned_washer", table_name="appointments")
    op.drop_table("consumable_refill_log", if_exists=True)
    # ### end Alembic commands ###
