"""add performance indexes

Revision ID: 29ed997a5e49
Revises: 71d216607c29
Create Date: 2026-06-15 19:34:49.754167

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29ed997a5e49"
down_revision: Union[str, Sequence[str], None] = "71d216607c29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_deleted_notifications_username",
        "deleted_notifications",
        ["username"],
        unique=False,
    )
    op.create_index(
        "ix_notification_queue_pending",
        "notification_queue",
        ["createdAt"],
        unique=False,
        sqlite_where=sa.text('"sentAt" IS NULL'),
        postgresql_where=sa.text('"sentAt" IS NULL'),
    )
    op.create_index(
        "ix_subscriptions_user_wash_type",
        "subscriptions",
        ["userId", "washTypeId"],
        unique=False,
    )
    op.create_index("ix_users_created_at", "users", ["createdAt"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_created_at", table_name="users")
    op.drop_index("ix_subscriptions_user_wash_type", table_name="subscriptions")
    op.drop_index(
        "ix_notification_queue_pending",
        table_name="notification_queue",
        sqlite_where=sa.text('"sentAt" IS NULL'),
        postgresql_where=sa.text('"sentAt" IS NULL'),
    )
    op.drop_index(
        "ix_deleted_notifications_username", table_name="deleted_notifications"
    )
    # ### end Alembic commands ###
