"""add appointment date column

Revision ID: 320f8f39854b
Revises: ad68b27e3a17
Create Date: 2026-06-13 20:15:00.057906

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "320f8f39854b"
down_revision: Union[str, Sequence[str], None] = "ad68b27e3a17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("date", sa.String(), nullable=True))

    # Populate date from existing dateTime values (YYYY-MM-DDTHH:mm:ss)
    op.execute(
        "UPDATE appointments SET date = substr(dateTime, 1, 10) WHERE date IS NULL"
    )

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.alter_column("date", existing_type=sa.String(), nullable=False)
        batch_op.create_index(
            batch_op.f("ix_appointments_date"), ["date"], unique=False
        )

    op.create_index("ix_cars_user", "cars", ["userId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cars_user", table_name="cars")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_date"))
        batch_op.drop_column("date")
    # ### end Alembic commands ###
