"""sync_model_diff

Revision ID: 42840ba4964a
Revises: 03d0cab39757
Create Date: 2026-06-26 00:19:08.621662

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42840ba4964a'
down_revision: Union[str, Sequence[str], None] = '03d0cab39757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_sqlite() -> bool:
    return op.get_bind().dialect.name == 'sqlite'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appointments_datetime', 'appointments', ['dateTime'], unique=False)
    op.create_index('ix_appointments_owner', 'appointments', ['ownerUsername'], unique=False)
    op.create_index('ix_appointments_owner_status', 'appointments', ['ownerUsername', 'status'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('ix_usage_log_appointment', 'consumable_usage_log', ['appointmentId'], unique=False)
    op.create_index('ix_usage_log_consumable', 'consumable_usage_log', ['consumableId'], unique=False)

    if _is_sqlite():
        with op.batch_alter_table('consumables', schema=None, recreate='always') as batch_op:
            batch_op.add_column(sa.Column('currentStock', sa.Float(), nullable=False, server_default=sa.text('0.0')))
            batch_op.add_column(sa.Column('minStock', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    else:
        op.add_column('consumables', sa.Column('currentStock', sa.Float(), nullable=False))
        op.add_column('consumables', sa.Column('minStock', sa.Float(), nullable=False))

    op.create_index('ix_logs_timestamp', 'logs', ['timestamp'], unique=False)
    op.create_index('ix_logs_username', 'logs', ['username'], unique=False)
    op.drop_index(op.f('ix_notification_queue_sentAt'), table_name='notification_queue')
    op.drop_index(op.f('ix_reviews_appointmentId'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_isPublished'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_userId'), table_name='reviews')

    if _is_sqlite():
        with op.batch_alter_table('reviews', schema=None, recreate='always') as batch_op:
            batch_op.create_foreign_key('fk_reviews_userId_users', 'users', ['userId'], ['id'])
    else:
        op.create_foreign_key(None, 'reviews', 'users', ['userId'], ['id'])

    if _is_sqlite():
        with op.batch_alter_table('users', schema=None, recreate='always') as batch_op:
            batch_op.add_column(sa.Column('avatarUrl', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('passwordVersion', sa.Integer(), nullable=False, server_default=sa.text('1')))
            batch_op.drop_index(op.f('ix_users_telegramId'))
            batch_op.drop_constraint(op.f('uq_users_referral_code'), type_='unique')
            batch_op.drop_index(op.f('ix_users_referralCode'))
            batch_op.create_index(op.f('ix_users_referralCode'), ['referralCode'], unique=True)
            batch_op.create_unique_constraint('uq_users_telegramId', ['telegramId'])
    else:
        op.add_column('users', sa.Column('avatarUrl', sa.String(), nullable=True))
        op.add_column('users', sa.Column('passwordVersion', sa.Integer(), nullable=False))
        op.drop_index(op.f('ix_users_telegramId'), table_name='users')
        op.drop_constraint(op.f('uq_users_referral_code'), 'users', type_='unique')
        op.drop_index(op.f('ix_users_referralCode'), table_name='users')
        op.create_index(op.f('ix_users_referralCode'), 'users', ['referralCode'], unique=True)
        op.create_unique_constraint(None, 'users', ['telegramId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _is_sqlite():
        with op.batch_alter_table('users', schema=None, recreate='always') as batch_op:
            batch_op.drop_constraint('uq_users_telegramId', type_='unique')
            batch_op.drop_index(op.f('ix_users_referralCode'))
            batch_op.create_unique_constraint(op.f('uq_users_referral_code'), ['referralCode'], postgresql_nulls_not_distinct=False)
            batch_op.create_index(op.f('ix_users_referralCode'), ['referralCode'], unique=False)
            batch_op.create_index(op.f('ix_users_telegramId'), ['telegramId'], unique=True)
            batch_op.drop_column('passwordVersion')
            batch_op.drop_column('avatarUrl')
    else:
        op.drop_constraint(None, 'users', type_='unique')
        op.drop_index(op.f('ix_users_referralCode'), table_name='users')
        op.create_index(op.f('ix_users_referralCode'), 'users', ['referralCode'], unique=False)
        op.create_unique_constraint(op.f('uq_users_referral_code'), 'users', ['referralCode'], postgresql_nulls_not_distinct=False)
        op.create_index(op.f('ix_users_telegramId'), 'users', ['telegramId'], unique=True)
        op.drop_column('users', 'passwordVersion')
        op.drop_column('users', 'avatarUrl')

    if _is_sqlite():
        with op.batch_alter_table('reviews', schema=None, recreate='always') as batch_op:
            batch_op.drop_constraint('fk_reviews_userId_users', type_='foreignkey')
    else:
        op.drop_constraint(None, 'reviews', type_='foreignkey')

    op.create_index(op.f('ix_reviews_userId'), 'reviews', ['userId'], unique=False)
    op.create_index(op.f('ix_reviews_isPublished'), 'reviews', ['isPublished'], unique=False)
    op.create_index(op.f('ix_reviews_appointmentId'), 'reviews', ['appointmentId'], unique=False)
    op.create_index(op.f('ix_notification_queue_sentAt'), 'notification_queue', ['sentAt'], unique=False)
    op.drop_index('ix_logs_username', table_name='logs')
    op.drop_index('ix_logs_timestamp', table_name='logs')

    if _is_sqlite():
        with op.batch_alter_table('consumables', schema=None, recreate='always') as batch_op:
            batch_op.drop_column('minStock')
            batch_op.drop_column('currentStock')
    else:
        op.drop_column('consumables', 'minStock')
        op.drop_column('consumables', 'currentStock')

    op.drop_index('ix_usage_log_consumable', table_name='consumable_usage_log')
    op.drop_index('ix_usage_log_appointment', table_name='consumable_usage_log')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_owner_status', table_name='appointments')
    op.drop_index('ix_appointments_owner', table_name='appointments')
    op.drop_index('ix_appointments_datetime', table_name='appointments')
    # ### end Alembic commands ###
