"""add shift_templates table

Revision ID: 9e5de8425124
Revises: 13bd1430d8f6
Create Date: 2026-06-15 12:17:30.960452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5de8425124'
down_revision: Union[str, Sequence[str], None] = '13bd1430d8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ownerUsername', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isDefault', sa.Boolean(), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_templates_owner', 'shift_templates', ['ownerUsername'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shift_templates_owner', table_name='shift_templates')
    op.drop_table('shift_templates')
    # ### end Alembic commands ###
