"""Add production indexes

Revision ID: ad68b27e3a17
Revises: 2026_06_10_add_email_to_users
Create Date: 2026-06-10 21:52:07.245122

"""
from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad68b27e3a17'
down_revision: Union[str, Sequence[str], None] = '2026_06_10_add_email_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appointments_box', 'appointments', ['box_index'], unique=False)
    op.create_index('ix_appointments_promo', 'appointments', ['promoId'], unique=False)
    op.create_index('ix_appointments_subscription', 'appointments', ['subscriptionId'], unique=False)
    op.create_index('ix_appointments_user', 'appointments', ['userId'], unique=False)
    op.create_index('ix_appointments_wash_type', 'appointments', ['washTypeId'], unique=False)
    op.create_index('ix_promos_wash_type', 'promos', ['washTypeId'], unique=False)
    op.create_index('ix_referrals_referred', 'referrals', ['referredId'], unique=False)
    op.create_index('ix_referrals_referrer', 'referrals', ['referrerId'], unique=False)
    op.create_index('ix_reviews_appointment', 'reviews', ['appointmentId'], unique=False)
    op.create_index('ix_reviews_published', 'reviews', ['isPublished'], unique=False)
    op.create_index('ix_reviews_user', 'reviews', ['userId'], unique=False)
    op.create_index('ix_services_category', 'services', ['category'], unique=False)
    op.create_index('ix_subscriptions_user', 'subscriptions', ['userId'], unique=False)
    op.create_index('ix_support_chats_admin', 'support_chats', ['assignedAdminId'], unique=False)
    op.create_index('ix_support_chats_last_message', 'support_chats', ['lastMessageAt'], unique=False)
    op.create_index('ix_support_chats_status', 'support_chats', ['status'], unique=False)
    op.create_index('ix_support_chats_user', 'support_chats', ['userId'], unique=False)
    op.create_index('ix_support_messages_chat', 'support_messages', ['chatId'], unique=False)
    op.create_index('ix_support_messages_created', 'support_messages', ['createdAt'], unique=False)
    op.create_index('ix_support_messages_sender', 'support_messages', ['senderId'], unique=False)
    op.create_index('ix_tips_appointment', 'tips', ['appointmentId'], unique=False)
    op.create_index('ix_tips_washer', 'tips', ['washerUsername'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_washer_notes_username', 'washer_notes', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_washer_notes_username', table_name='washer_notes')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_tips_washer', table_name='tips')
    op.drop_index('ix_tips_appointment', table_name='tips')
    op.drop_index('ix_support_messages_sender', table_name='support_messages')
    op.drop_index('ix_support_messages_created', table_name='support_messages')
    op.drop_index('ix_support_messages_chat', table_name='support_messages')
    op.drop_index('ix_support_chats_user', table_name='support_chats')
    op.drop_index('ix_support_chats_status', table_name='support_chats')
    op.drop_index('ix_support_chats_last_message', table_name='support_chats')
    op.drop_index('ix_support_chats_admin', table_name='support_chats')
    op.drop_index('ix_subscriptions_user', table_name='subscriptions')
    op.drop_index('ix_services_category', table_name='services')
    op.drop_index('ix_reviews_user', table_name='reviews')
    op.drop_index('ix_reviews_published', table_name='reviews')
    op.drop_index('ix_reviews_appointment', table_name='reviews')
    op.drop_index('ix_referrals_referrer', table_name='referrals')
    op.drop_index('ix_referrals_referred', table_name='referrals')
    op.drop_index('ix_promos_wash_type', table_name='promos')
    op.drop_index('ix_appointments_wash_type', table_name='appointments')
    op.drop_index('ix_appointments_user', table_name='appointments')
    op.drop_index('ix_appointments_subscription', table_name='appointments')
    op.drop_index('ix_appointments_promo', table_name='appointments')
    op.drop_index('ix_appointments_box', table_name='appointments')
    # ### end Alembic commands ###
