"""initial schema

Revision ID: c1f6857490b2
Revises:
Create Date: 2026-05-30 00:36:10.650020

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1f6857490b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumables",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "deleted_notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("createdAt", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "extra_favorites",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("serviceId", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("username", "serviceId"),
    )
    op.create_table(
        "fcm_tokens",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("updatedAt", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("details", sa.String(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_favorites",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("serviceId", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("username", "serviceId"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("durationMinutes", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("isFavorite", sa.Integer(), nullable=False),
        sa.Column("isFromApi", sa.Integer(), nullable=False),
        sa.Column("updatedAt", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("passwordHash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("displayName", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("carModel", sa.String(), nullable=False),
        sa.Column("carNumber", sa.String(), nullable=False),
        sa.Column("createdAt", sa.String(), nullable=False),
        sa.Column("isFavoriteAdmin", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "wash_types",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("basePrice", sa.Integer(), nullable=False),
        sa.Column("durationMinutes", sa.Integer(), nullable=False),
        sa.Column("sortOrder", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "washer_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("isRead", sa.Integer(), nullable=False),
        sa.Column("createdAt", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("washTypeId", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("discountPercent", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("weekendOnly", sa.Boolean(), nullable=False),
        sa.Column("fetchedAt", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["washTypeId"],
            ["wash_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_consumables",
        sa.Column("serviceId", sa.String(), nullable=False),
        sa.Column("consumableId", sa.String(), nullable=False),
        sa.Column("quantity_per_service", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumableId"],
            ["consumables.id"],
        ),
        sa.ForeignKeyConstraint(
            ["serviceId"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("serviceId", "consumableId"),
    )
    op.create_table(
        "wash_type_consumables",
        sa.Column("washTypeId", sa.String(), nullable=False),
        sa.Column("consumableId", sa.String(), nullable=False),
        sa.Column("quantity_per_service", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["consumableId"], ["consumables.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["washTypeId"], ["wash_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("washTypeId", "consumableId"),
    )
    op.create_table(
        "wash_type_included_extras",
        sa.Column("washTypeId", sa.String(), nullable=False),
        sa.Column("extraServiceId", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraServiceId"], ["services.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["washTypeId"], ["wash_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("washTypeId", "extraServiceId"),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("clientName", sa.String(), nullable=False),
        sa.Column("carModel", sa.String(), nullable=False),
        sa.Column("carNumber", sa.String(), nullable=False),
        sa.Column("dateTime", sa.String(), nullable=False),
        sa.Column("washTypeId", sa.String(), nullable=False),
        sa.Column("additionalServices", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("isFavorite", sa.Integer(), nullable=False),
        sa.Column("ownerUsername", sa.String(), nullable=False),
        sa.Column("isHiddenFromAdmin", sa.Boolean(), nullable=False),
        sa.Column("promoPrice", sa.Integer(), nullable=False),
        sa.Column("paidPrice", sa.Integer(), nullable=False),
        sa.Column("isModifiedByAdmin", sa.Integer(), nullable=False),
        sa.Column("isModifiedByWasher", sa.Integer(), nullable=False),
        sa.Column("isSeenByClient", sa.Integer(), nullable=False),
        sa.Column("originalPrice", sa.Integer(), nullable=False),
        sa.Column("assignedWasher", sa.String(), nullable=False),
        sa.Column("promoId", sa.String(), nullable=True),
        sa.Column("box_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promoId"],
            ["promos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["washTypeId"],
            ["wash_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promo_included_extras",
        sa.Column("promoId", sa.String(), nullable=False),
        sa.Column("extraServiceId", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extraServiceId"], ["services.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["promoId"], ["promos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("promoId", "extraServiceId"),
    )
    op.create_table(
        "consumable_usage_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("appointmentId", sa.String(), nullable=False),
        sa.Column("consumableId", sa.String(), nullable=False),
        sa.Column("quantityUsed", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointmentId"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consumableId"],
            ["consumables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Alembic's default alembic_version.version_num column is VARCHAR(32), but
    # this project uses descriptive revision ids that can be longer. Widen the
    # column early so that version updates on PostgreSQL do not truncate.
    if op.get_context().dialect.name == "postgresql":
        op.execute(
            sa.text("ALTER TABLE alembic_version ALTER COLUMN version_num TYPE VARCHAR(255)")
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consumable_usage_log")
    op.drop_table("promo_included_extras")
    op.drop_table("appointments")
    op.drop_table("wash_type_included_extras")
    op.drop_table("wash_type_consumables")
    op.drop_table("service_consumables")
    op.drop_table("promos")
    op.drop_table("washer_notes")
    op.drop_table("wash_types")
    op.drop_table("users")
    op.drop_table("services")
    op.drop_table("service_favorites")
    op.drop_table("logs")
    op.drop_table("fcm_tokens")
    op.drop_table("extra_favorites")
    op.drop_table("deleted_notifications")
    op.drop_table("consumables")
    # ### end Alembic commands ###
