/// Простая fallback-локализация (RU / EN).
/// Полная локализация через ARB — отдельная задача.
class AppStrings {
  static const _ru = <String, String>{
    'app_name': 'LanWash',
    'login_title': 'Вход в систему',
    'login_subtitle': 'Введите ваши данные для входа',
    'login_field_login': 'Логин',
    'login_field_login_hint': 'Введите логин',
    'login_field_password': 'Пароль',
    'login_field_password_hint': 'Введите пароль',
    'login_button': 'Войти',
    'login_no_account': 'Нет аккаунта? Зарегистрироваться',
    'login_resume_title': 'С возвращением',
    'login_resume_button': 'Продолжить',
    'login_switch_account': 'Войти под другим пользователем',
    'login_switch_dialog_title': 'Сменить аккаунт',
    'login_switch_dialog_body': 'Вы уверены, что хотите выйти из текущего аккаунта?',
    'cancel': 'Отмена',
    'logout': 'Выйти',
    'register_title': 'Регистрация',
    'register_subtitle': 'Заполните данные для регистрации',
    'register_field_name': 'Ваше имя',
    'register_field_login': 'Логин',
    'register_field_login_hint': 'только латиница и цифры',
    'register_field_password': 'Пароль',
    'register_field_phone': 'Телефон',
    'register_field_phone_hint': '+7 (999) 000-00-00',
    'register_button': 'Зарегистрироваться',
    'register_has_account': 'Уже есть аккаунт? Войти',
    'theme': 'Тема',
    'language': 'Язык',
    'validation_required': 'Обязательное поле',
    'validation_login_short': 'Минимум 3 символа',
    'validation_password_short': 'Минимум 8 символов',
    'validation_password_upper': 'Хотя бы одна заглавная буква',
    'validation_password_lower': 'Хотя бы одна строчная буква',
    'validation_password_digit': 'Хотя бы одна цифра',
    'validation_password_special': 'Хотя бы один спецсимвол (@\$!%*?&_)',
    'validation_phone_short': 'Введите полный номер (+7 и 10 цифр)',
    'error': 'Ошибка',
  };

  static const _en = <String, String>{
    'app_name': 'LanWash',
    'login_title': 'Sign in',
    'login_subtitle': 'Enter your credentials',
    'login_field_login': 'Login',
    'login_field_login_hint': 'Enter login',
    'login_field_password': 'Password',
    'login_field_password_hint': 'Enter password',
    'login_button': 'Sign in',
    'login_no_account': "Don't have an account? Sign up",
    'login_resume_title': 'Welcome back',
    'login_resume_button': 'Continue',
    'login_switch_account': 'Switch account',
    'login_switch_dialog_title': 'Switch account',
    'login_switch_dialog_body': 'Are you sure you want to log out?',
    'cancel': 'Cancel',
    'logout': 'Log out',
    'register_title': 'Sign up',
    'register_subtitle': 'Fill in your details',
    'register_field_name': 'Your name',
    'register_field_login': 'Login',
    'register_field_login_hint': 'latin letters and digits only',
    'register_field_password': 'Password',
    'register_field_phone': 'Phone',
    'register_field_phone_hint': '+7 (999) 000-00-00',
    'register_button': 'Sign up',
    'register_has_account': 'Already have an account? Sign in',
    'theme': 'Theme',
    'language': 'Language',
    'validation_required': 'Required',
    'validation_login_short': 'Minimum 3 characters',
    'validation_password_short': 'Minimum 8 characters',
    'validation_password_upper': 'At least one uppercase letter',
    'validation_password_lower': 'At least one lowercase letter',
    'validation_password_digit': 'At least one digit',
    'validation_password_special': 'At least one special character (@\$!%*?&_)',
    'validation_phone_short': 'Enter full number (+7 and 10 digits)',
    'error': 'Error',
  };

  static String of(String key, String lang) {
    final map = lang == 'en' ? _en : _ru;
    return map[key] ?? key;
  }
}
