#!/usr/bin/env python3
"""Generate Prometheus web.config.yml with bcrypt-hashed basic auth user.

Run before deploying:
    PROMETHEUS_USER=admin PROMETHEUS_PASSWORD='secret' python3 scripts/generate_prometheus_web_config.py

The output file is referenced from docker-compose.yml and must not be committed.
"""

import os
from pathlib import Path

import bcrypt


def main() -> None:
    user = os.getenv("PROMETHEUS_USER")
    password = os.getenv("PROMETHEUS_PASSWORD")

    if not user or not password:
        raise SystemExit(
            "PROMETHEUS_USER and PROMETHEUS_PASSWORD environment variables are required"
        )

    hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=12)).decode()

    project_root = Path(__file__).resolve().parent.parent
    output_path = project_root / "prometheus" / "web.config.yml"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(
        f"# Auto-generated by scripts/generate_prometheus_web_config.py\n"
        f"# DO NOT COMMIT THIS FILE.\n"
        f"basic_auth_users:\n"
        f"  {user}: {hashed}\n",
        encoding="utf-8",
    )

    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
